# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=3.2.6
FROM docker.io/library/ruby:$RUBY_VERSION-slim

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev

RUN mkdir /work
WORKDIR /work

COPY Gemfile /work/Gemfile
COPY Gemfile.lock /work/Gemfile.lock
RUN bundle install

COPY . /work
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
CMD ["sh", "-c", "bin/rails dartsass:watch & bin/rails server -b 0.0.0.0"]
