# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=3.2.6
FROM docker.io/library/ruby:$RUBY_VERSION-slim

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev

RUN mkdir /work
WORKDIR /work

COPY Gemfile /work/Gemfile
COPY Gemfile.lock /work/Gemfile.lock
RUN bundle install

COPY . /work

EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0"]
